From 0981a4bc273e2a87ad10c602d9547e006e06d8dd Mon Sep 17 00:00:00 2001
From: Mariusz Felisiak <felisiak.mariusz@gmail.com>
Date: Fri, 7 Apr 2023 11:07:54 +0200
Subject: [PATCH] Refs #34118 -- Fixed CustomChoicesTests.test_uuid_unsupported
 on Python 3.11.4+.

https://github.com/python/cpython/commit/5342f5e713e0cc45b6f226d2d053a8cde1b4d68e

Follow up to 38e63c9e61152682f3ff982c85a73793ab6d3267.
---
 tests/model_enums/tests.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/tests/model_enums/tests.py b/tests/model_enums/tests.py
index ffc199ce42..c4ca6c91d7 100644
--- a/tests/model_enums/tests.py
+++ b/tests/model_enums/tests.py
@@ -259,7 +259,7 @@ class CustomChoicesTests(SimpleTestCase):
                 pass
 
     def test_uuid_unsupported(self):
-        msg = 'UUID objects are immutable'
-        with self.assertRaisesMessage(TypeError, msg):
+        with self.assertRaises(TypeError):
+
             class Identifier(uuid.UUID, models.Choices):
                 A = '972ce4eb-a95f-4a56-9339-68c208a76f18'
-- 
2.40.1

