https://bugs.gentoo.org/898708
https://github.com/shapely/shapely/pull/1872
https://github.com/shapely/shapely/commit/fea6d0351a4422b1f9fefb508db7924981c18e43

From fea6d0351a4422b1f9fefb508db7924981c18e43 Mon Sep 17 00:00:00 2001
From: Joris Van den Bossche <jorisvandenbossche@gmail.com>
Date: Sun, 8 Oct 2023 11:12:28 +0200
Subject: [PATCH] Fix for cython 3 compatibility (#1872)

--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,6 +1,6 @@
 [build-system]
 requires = [
-    "Cython~=0.29",
+    "Cython",
     "oldest-supported-numpy",
     "setuptools>=61.0.0",
 ]
--- a/shapely/_geos.pyx
+++ b/shapely/_geos.pyx
@@ -8,7 +8,7 @@ import warnings
 from shapely import GEOSException
 
 
-cdef void geos_message_handler(const char* message, void* userdata):
+cdef void geos_message_handler(const char* message, void* userdata) noexcept:
     snprintf(<char *>userdata, 1024, "%s", message)
 
 
